// ###############################################
// ## THIS FILE WILL BE AUTOGENERATED USING EOLIAN
// ###############################################


// enums
// #define ECORE_CALLBACK_RENEW ...
// #define ECORE_CALLBACK_PASS_ON ...
// #define ECORE_CALLBACK_DONE ...

// typedef enum {
    // ELM_WIN_UNKNOWN,
    // ELM_WIN_BASIC,
    // ELM_WIN_DIALOG_BASIC,
    // ...
// } Elm_Win_Type; // TODO COMPLETE


// typedefs
typedef Eo Evas_Object;
// typedef Eina_Bool(*Ecore_Task_Cb) (void *data);

// functions
int evas_init(void);
int evas_shutdown(void);


// Evas.Object
// Eina_Bool elm_obj_layout_text_set(Eo *obj, const char * part, const char *text);
// const char *elm_obj_layout_text_get(const Eo *obj, const char * part);


// Evas.Object_Smart

// Evas.Clickable_Interface
typedef Eo Evas_Clickable_Interface;
const Eo_Class *evas_clickable_interface_interface_get(void);
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_CLICKED;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_CLICKED_DOUBLE;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_CLICKED_TRIPLE;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_CLICKED_RIGHT;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_PRESSED;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_UNPRESSED;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_LONGPRESSED;
extern const Eo_Event_Description _EVAS_CLICKABLE_INTERFACE_EVENT_REPEATED;


